name: ocr-chunking

services:
  api:
    image: ocr-chunking:latest
    container_name: ocr-chunking-api
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ..:/workspace
    # command: [ "tail", "-f", "/dev/null" ]